name: GitHub Actions Demo
run-name: ${{ github.actor }} is running Python test suite 🐍
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Install Python requirements
        run: pip install -r requirements.txt
      - name: Running Python tests
        run: |
          python -m unittest discover
      - run: echo "🍏 This job's status is ${{ job.status }}."
